name: Continuous Integration
on:
  pull_request:
    branches:
      - master

jobs: 
  flutter_test:
    name: Run flutter tests and analyze
    runs-on:  ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with: 
          java_version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
